#!/bin/bash

# You can place this file in ~/.local/bin and make it executable with chmod +x ~/.local/bin/alemhist
# Alternatively, you can make an alias in your .bashrc or .bash_aliases with the alias command

# Personnalize this command :
# - set the path where the alemhist.py script is located
# - add alemhist.py options --no-color, --max-count and --reverse
# - change less options, replace it by more or remove it completely
# Warning: using -v and -r options on alembic history may make alemhist crash

alembic history --indicate-current | python3 ~/alemhist/alemhist.py --color $@ | less --RAW-CONTROL-CHARS --no-init --quit-if-one-screen
