#!/bin/bash

current_rev=$1
new_base=$2

# Parameters should follow the right pattern: 12 hexadecimal characters corresponding to revision hashes
if [[ ! $current_rev =~ [0-9a-f]{12} || ! $new_base =~ [0-9a-f]{12} ]]; then
	echo 'Usage: ale rebase <current_rev> <new_base>'
	echo 'current_rev: hash of the revision to rebase'
	echo 'new_base: hash of the new base revision'
	exit 1
fi

# Find setter for script_location in file alembic.ini, and execute it
source <(grep script_location alembic.ini | sed 's/ *= */=/g')

# Change the base revision hash in the script of the current revision
sed -i -E "s/Revises: [0-9a-f]{12}/Revises: $new_base/" $script_location/versions/$current_rev*.py
sed -i -E "s/down_revision = \"[0-9a-f]{12}\"/down_revision = \"$new_base\"/" $script_location/versions/$current_rev*.py

